name: "CI/CD E2E Tests"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: choice
        options: [dev, test, preprod]

jobs:
  listS3:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/service-roles/github-actions-api-deployment-role
          aws-region: eu-west-2

      - name: List S3 bucket
        run: |
          aws s3 ls s3://eligibility-signposting-api-${{ inputs.environment }}-tfstate

      - name: Run Behave tests
        run: |
          mkdir -p reports
          poetry run behave --format json --outfile reports/behave-report.json

      - name: Upload Behave test results
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-results
          path: reports/
